const colors = {
  background: "var(--color-background)",
  content: "var(--color-content)",
  "base-100": "var(--color-base-100)",
  "base-100-content": "var(--color-base-100-content)",
  "base-200": "var(--color-base-200)",
  "base-200-content": "var(--color-base-200-content)",
  "base-300": "var(--color-base-300)",
  "base-300-content": "var(--color-base-300-content)",
  "base-400": "var(--color-base-400)",
  "base-400-content": "var(--color-base-400-content)",
  primary: "var(--color-primary)",
  "primary-content": "var(--color-primary-content)",
  secondary: "var(--color-secondary)",
  "secondary-content": "var(--color-secondary-content)",
  default: "var(--color-default)",
  "default-content": "var(--color-default-content)",
  info: "var(--color-info)",
  "info-content": "var(--color-info-content)",
  success: "var(--color-success)",
  "success-content": "var(--color-success-content)",
  warning: "var(--color-warning)",
  "warning-content": "var(--color-warning-content)",
  danger: "var(--color-danger)",
  "danger-content": "var(--color-danger-content)",
  border: "var(--color-border)",
};

export default colors;
